# Generated by Django 5.1.6 on 2025-03-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_newsarticle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
