# Generated by Django 5.1.6 on 2025-04-07 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mission_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
