# Generated by Django 5.1.6 on 2025-04-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
