# Generated by Django 5.1.6 on 2025-04-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mission_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_realtime',
            field=models.BooleanField(default=False),
        ),
    ]
