# Generated by Django 5.1.6 on 2025-04-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mission_is_realtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
