# Generated by Django 5.1.6 on 2025-05-26 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_reset_token_user_reset_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
